openapi: 3.0.2
info:
  contact:
    email: thomas.schaffter@sagebionetworks.org
    name: The NLP Sandbox Team
    url: https://nlpsandbox.github.io/nlpsandbox-schemas
  description: |
    The OpenAPI specification implemented by NLP Sandbox PHI Deidentifiers.
    # Overview
    TBA
  license:
    name: Apache 2.0
    url: https://nlpsandbox.github.io/nlpsandbox-schemas/blob/develop/LICENSE
  title: NLP Sandbox Deidentifier API
  version: 0.2.2
  x-logo:
    url: https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png
servers:
- url: http://example.com/api/v1
- url: https://example.com/api/v1
tags:
- description: Operations about deidentified notes
  name: DeidentifiedNotes
- description: Operations about this API service
  name: Service
paths:
  /deidentifiedNotes:
    post:
      description: Returns the deidentified note
      operationId: create_deidentified_notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeidentifyRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeidentifyResponse'
          description: Success
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
      summary: Deidentify a clinical note
      tags:
      - DeidentifiedNotes
      x-openapi-router-controller: openapi_server.controllers.deidentified_notes_controller
  /service:
    get:
      description: Get information about the service
      operationId: service
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
          description: Success
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
      summary: Get service information
      tags:
      - Service
      x-openapi-router-controller: openapi_server.controllers.service_controller
components:
  responses:
    Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Unauthorized
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource was not found
  schemas:
    DeidentificationConfig:
      description: Configuration of one deidentification strategy and a list of annotation
        types to apply it to.
      example:
        confidenceThreshold: 42.4
        deidentificationStrategy:
          redactConfig: '{}'
          annotationTypeConfig: '{}'
          maskingCharConfig:
            maskingChar: '*'
          dateOffsetConfig:
            offsetDays: 0
        annotationTypes:
        - text_physical_address
        - text_physical_address
      properties:
        confidenceThreshold:
          default: 0
          description: The minimum confidence level for a given annotation to be de-identified
          example: 42.4
          format: float
          maximum: 100
          minimum: 0
          type: number
        deidentificationStrategy:
          $ref: '#/components/schemas/DeidentificationConfig_deidentificationStrategy'
        annotationTypes:
          description: the types of annotations to which the de-identifer should apply
            the selected strategy
          items:
            enum:
            - text_physical_address
            - text_date
            - text_person_name
            type: string
          type: array
      type: object
    Note:
      description: A clinical note
      example:
        noteType: loinc:LP29684-5
        patientId: 507f1f77bcf86cd799439011
        id: id
        text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
      properties:
        id:
          description: The ID of the note
          readOnly: true
          type: string
        text:
          description: The content of the clinical note
          example: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
          type: string
        noteType:
          description: The note type (LOINC concept)
          example: loinc:LP29684-5
          type: string
        patientId:
          description: The patient ID
          example: 507f1f77bcf86cd799439011
          type: string
      required:
      - noteType
      - text
      type: object
    DeidentifyRequest:
      description: A request to de-identify a note
      example:
        note:
          noteType: loinc:LP29684-5
          patientId: 507f1f77bcf86cd799439011
          id: id
          text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
        deidentificationConfigurations:
        - confidenceThreshold: 42.4
          deidentificationStrategy:
            redactConfig: '{}'
            annotationTypeConfig: '{}'
            maskingCharConfig:
              maskingChar: '*'
            dateOffsetConfig:
              offsetDays: 0
          annotationTypes:
          - text_physical_address
          - text_physical_address
        - confidenceThreshold: 42.4
          deidentificationStrategy:
            redactConfig: '{}'
            annotationTypeConfig: '{}'
            maskingCharConfig:
              maskingChar: '*'
            dateOffsetConfig:
              offsetDays: 0
          annotationTypes:
          - text_physical_address
          - text_physical_address
      properties:
        deidentificationConfigurations:
          description: A list of deidentification strategies and the entity types
            on which to perform them. De-identification priority (i.e. which annotation
            to use when two annotations overlap) is determined by the order of this
            array and the order of the annotationTypes array inside of each deidentificationConfig.
          items:
            $ref: '#/components/schemas/DeidentificationConfig'
          type: array
        note:
          $ref: '#/components/schemas/Note'
      required:
      - note
      type: object
    ResourceSource:
      description: An API resource source
      example:
        name: name
      properties:
        name:
          description: Full path of an API resource
          type: string
      type: object
    AnnotationSource:
      description: The source of an annotation record
      example:
        resourceSource:
          name: name
      properties:
        resourceSource:
          $ref: '#/components/schemas/ResourceSource'
      type: object
    TextAnnotation:
      description: An annotation in a text
      properties:
        start:
          description: The position of the first character
          example: 42
          type: integer
        length:
          description: The length of the annotation
          example: 10
          type: integer
        text:
          description: The string annotated
          type: string
        confidence:
          description: The confidence in the accuracy of the annotation
          example: 95
          format: float
          maximum: 100
          minimum: 0
          type: number
      required:
      - length
      - start
      type: object
    TextDateAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextDateAnnotation_allOf'
      description: A date annotation in a text
      example:
        start: 42
        length: 10
        text: 10/26/2020
        dateFormat: MM/DD/YYYY
      type: object
    TextPersonNameAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      description: A person name annotation in a text
      example:
        start: 42
        length: 11
        text: Chloe Price
      type: object
    TextPhysicalAddressAnnotation:
      allOf:
      - $ref: '#/components/schemas/TextAnnotation'
      - $ref: '#/components/schemas/TextPhysicalAddressAnnotation_allOf'
      description: A person name annotation in a text
      example:
        start: 42
        length: 11
        text: Seattle
        addressType: city
      type: object
    Annotation:
      description: An annotation record
      example:
        textDateAnnotations:
        - start: 42
          length: 10
          text: 10/26/2020
          dateFormat: MM/DD/YYYY
        - start: 42
          length: 10
          text: 10/26/2020
          dateFormat: MM/DD/YYYY
        textPersonNameAnnotations:
        - start: 42
          length: 11
          text: Chloe Price
        - start: 42
          length: 11
          text: Chloe Price
        textPhysicalAddressAnnotations:
        - start: 42
          length: 11
          text: Seattle
          addressType: city
        - start: 42
          length: 11
          text: Seattle
          addressType: city
        annotationSource:
          resourceSource:
            name: name
        name: name
      properties:
        name:
          description: Resource name of the annotation record, of the form datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations/{annotationId}
          readOnly: true
          type: string
        annotationSource:
          $ref: '#/components/schemas/AnnotationSource'
        textDateAnnotations:
          description: Date annotations in a text
          items:
            $ref: '#/components/schemas/TextDateAnnotation'
          type: array
        textPersonNameAnnotations:
          description: Person name annotations in a text
          items:
            $ref: '#/components/schemas/TextPersonNameAnnotation'
          type: array
        textPhysicalAddressAnnotations:
          description: Physical address annotations in a text
          items:
            $ref: '#/components/schemas/TextPhysicalAddressAnnotation'
          type: array
      type: object
    DeidentifyResponse:
      description: Response to deidentification request
      example:
        deidentifiedAnnotations:
          textDateAnnotations:
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          textPersonNameAnnotations:
          - start: 42
            length: 11
            text: Chloe Price
          - start: 42
            length: 11
            text: Chloe Price
          textPhysicalAddressAnnotations:
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          annotationSource:
            resourceSource:
              name: name
          name: name
        deidentifiedNote:
          noteType: loinc:LP29684-5
          patientId: 507f1f77bcf86cd799439011
          id: id
          text: On 12/26/2020, Ms. Chloe Price met with Dr. Prescott.
        originalAnnotations:
          textDateAnnotations:
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          - start: 42
            length: 10
            text: 10/26/2020
            dateFormat: MM/DD/YYYY
          textPersonNameAnnotations:
          - start: 42
            length: 11
            text: Chloe Price
          - start: 42
            length: 11
            text: Chloe Price
          textPhysicalAddressAnnotations:
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          - start: 42
            length: 11
            text: Seattle
            addressType: city
          annotationSource:
            resourceSource:
              name: name
          name: name
      properties:
        originalAnnotations:
          $ref: '#/components/schemas/Annotation'
        deidentifiedAnnotations:
          $ref: '#/components/schemas/Annotation'
        deidentifiedNote:
          $ref: '#/components/schemas/Note'
      type: object
    Error:
      description: Problem details (tools.ietf.org/html/rfc7807)
      properties:
        title:
          description: A human readable documentation for the problem type
          type: string
        status:
          description: The HTTP status code
          type: integer
        detail:
          description: A human readable explanation specific to this occurrence of
            the problem
          type: string
        type:
          description: An absolute URI that identifies the problem type
          type: string
      required:
      - status
      - title
      type: object
    Service:
      description: Information about an NLP service
      example:
        license: apache-2.0
        authorEmail: author@example.com
        author: Example Author
        name: awesome-date-annotator
        description: An awesome Date Annotator based on regex patterns
        repository: github:awesome-org/awesome-date-annotator
        version: 1.0.0
        url: https://openapi-generator.tech
      properties:
        name:
          description: The service name
          example: awesome-date-annotator
          maxLength: 60
          minLength: 3
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
          type: string
        version:
          description: The version of the service (SemVer string)
          example: 1.0.0
          minLength: 1
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          type: string
        license:
          description: The license of this service (spdx.org/licenses Identifier)
          enum:
          - afl-3.0
          - apache-2.0
          - artistic-2.0
          - bsl-1.0
          - bsd-2-clause
          - bsd-3-clause
          - bsd-3-clause-clear
          - cc
          - cc0-1.0
          - cc-by-4.0
          - cc-by-sa-4.0
          - wtfpl
          - ecl-2.0
          - epl-1.0
          - epl-2.0
          - eupl-1.1
          - agpl-3.0
          - gpl
          - gpl-2.0
          - gpl-3.0
          - lgpl
          - lgpl-2.1
          - lgpl-3.0
          - isc
          - lppl-1.3c
          - ms-pl
          - mit
          - mpl-2.0
          - osl-3.0
          - postgresql
          - ofl-1.1
          - ncsa
          - unlicense
          - zlib
          example: apache-2.0
          type: string
        repository:
          description: The place where the code lives
          example: github:awesome-org/awesome-date-annotator
          type: string
        description:
          description: A short, one-sentence summary of the service
          example: An awesome Date Annotator based on regex patterns
          maxLength: 100
          type: string
        author:
          description: The author of the service
          example: Example Author
          type: string
        authorEmail:
          description: The email address of the author
          example: author@example.com
          format: email
          type: string
        url:
          description: The URL to the homepage of the service
          format: uri
          type: string
      type: object
    DeidentificationConfig_deidentificationStrategy_maskingCharConfig:
      description: Configuration for the masking char strategy. E.g. "John Smith lives
        at 123 Main St" -> "********* lives at ***********".
      example:
        maskingChar: '*'
      properties:
        maskingChar:
          default: '*'
          description: Character used to mask annotated PII text.
          maxLength: 1
          minLength: 1
          type: string
    DeidentificationConfig_deidentificationStrategy_dateOffsetConfig:
      description: Configuration for the "date offset" strategy. E.g. "John Smith
        visited on 1 January 2020" -> "John Smith visited on 29 October 2025". Note,
        can only be set with the "text_date" annotation type.
      example:
        offsetDays: 0
      properties:
        offsetDays:
          description: Number of days by which to offset annotated dates.
          type: integer
    DeidentificationConfig_deidentificationStrategy:
      description: The strategy used to de-identify the note's text. Only one field
        may be set.
      example:
        redactConfig: '{}'
        annotationTypeConfig: '{}'
        maskingCharConfig:
          maskingChar: '*'
        dateOffsetConfig:
          offsetDays: 0
      properties:
        maskingCharConfig:
          $ref: '#/components/schemas/DeidentificationConfig_deidentificationStrategy_maskingCharConfig'
        redactConfig:
          description: Configuration for the redaction strategy. E.g. "John Smith
            lives at 123 Main St" -> "lives at".
          type: object
        annotationTypeConfig:
          description: Configuration for the "annotation type" strategy. E.g. "John
            Smith lives at 123 Main St" -> "[PERSON_NAME] lives at [PHYSICAL_ADDRESS]".
          type: object
        dateOffsetConfig:
          $ref: '#/components/schemas/DeidentificationConfig_deidentificationStrategy_dateOffsetConfig'
    TextDateAnnotation_allOf:
      properties:
        dateFormat:
          description: Date format (ISO 8601)
          example: MM/DD/YYYY
          type: string
    TextPhysicalAddressAnnotation_allOf:
      properties:
        addressType:
          description: Type of address information
          enum:
          - city
          - country
          - department
          - hospital
          - organization
          - other
          - room
          - state
          - street
          - zip
          type: string
